name: Prepare and build node

on:
  pull_request:
    branches: [main]

jobs:
  build_node:
    uses: CorporalCiprian/todo-template/.github/workflows/build-and-test-node.yml@main
    with: 
      version: '24'