name: Prepare and build node

on:
  pull_request:
    branches: [main]

jobs:
  validate_branch:
    uses: CorporalCiprian/todo-template/.github/workflows/check-branch-naming-convention.yml@main
    with:
      branch: ${{ github.event.pull_request.head.ref }}

  build_node:
    needs: validate_branch
    uses: CorporalCiprian/todo-template/.github/workflows/build-and-test-node.yml@main
    with: 
      version: '24'