on:
  push:
    tags:
      - 'v*'
    branches: [main]

jobs:
  deploy_to_test:
    uses: CorporalCiprian/todo-template/.github/workflows/deploy-template.yml@main
    with:
      env: Test
    