on:
  push:
    tags:
      - v*

jobs:
  deploy_to_test:
    uses: CorporalCiprian/todo-template/.github/workflows/deploy-app-node.yml@main
    with:
      env: Test
      deploy: false
      node-version: '24'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    