on:
  push:
    tags:
      - v*

jobs:
  deploy_to_test:
    uses: CorporalCiprian/todo-template/.github/workflows/deploy-app-node.yml@main
    with:
      env: Test
      deploy: false
    